[azure]
vm_azure ansible_host=20.74.80.224 ansible_user=Ybouzafo ansible_ssh_private_key_file=/home/ybouzafo/Desktop/SecretFiles/Ybouzafo_key.pem custom_domain_name=ybouzafo.francecentral.cloudapp.azure.com

[digital_ocean]
vm_do ansible_host=146.190.77.157 ansible_user=shilal ansible_ssh_private_key_file=/home/ybouzafo/.ssh/id_ed25519 custom_domain_name=shilal.duckdns.org